server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: students-service
          uri: lb://students
          predicates:
            - Path=/students/**

        - id: schools-service
          uri: lb://schools
          predicates:
            - Path=/schools/**

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka