server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/chris/IdeaProjects/project_microservices/config-server/src/main/resources/configurations

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
